config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :order
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :size
  belongs_to :item_state
  belongs_to :prefecture
end

app/models/item_state.rb
class ItemState < ActiveHash::Base
  self.data =[
    { id: 1, name: '--' },
    { id: 2, name: '新品・未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
 ]
 include ActiveHash::Associations
 has_many :items

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '--'},
    {id: 2, name: '北海道'}, {id: 3, name: '青森県'}, {id: 4, name: '岩手県'},
    {id: 5, name: '宮城県'}, {id: 6, name: '秋田県'}, {id: 7, name: '山形県'},
    {id: 8, name: '福島県'}, {id: 9, name: '茨城県'}, {id: 10, name: '栃木県'},
    {id: 11, name: '群馬県'}, {id: 12, name: '埼玉県'}, {id: 13, name: '千葉県'},
    {id: 14, name: '東京都'}, {id: 15, name: '神奈川県'}, {id: 16, name: '新潟県'},
    {id: 17, name: '富山県'}, {id: 18, name: '石川県'}, {id: 19, name: '福井県'},
    {id: 20, name: '山梨県'}, {id: 21, name: '長野県'}, {id: 22, name: '岐阜県'},
    {id: 23, name: '静岡県'}, {id: 24, name: '愛知県'}, {id: 25, name: '三重県'},
    {id: 26, name: '滋賀県'}, {id: 27, name: '京都府'}, {id: 28, name: '大阪府'},
    {id: 29, name: '兵庫県'}, {id: 30, name: '奈良県'}, {id: 31, name: '和歌山県'},
    {id: 32, name: '鳥取県'}, {id: 33, name: '島根県'}, {id: 34, name: '岡山県'},
    {id: 35, name: '広島県'}, {id: 36, name: '山口県'}, {id: 37, name: '徳島県'},
    {id: 38, name: '香川県'}, {id: 39, name: '愛媛県'}, {id: 40, name: '高知県'},
    {id: 41, name: '福岡県'}, {id: 42, name: '佐賀県'}, {id: 43, name: '長崎県'},
    {id: 44, name: '熊本県'}, {id: 45, name: '大分県'}, {id: 46, name: '宮崎県'},
    {id: 47, name: '鹿児島県'}, {id: 48, name: '沖縄県'}
  ]
  include ActiveHash::Associations
  has_many :items


end

app/models/size.rb
class Size < ActiveHash::Base
  self.data =[
   { id: 1, name: '--' },
   { id: 2, name: '22cm' },
   { id: 3, name: '22.5cm' },
   { id: 4, name: '23cm' },
   { id: 5, name: '23.5cm' },
   { id: 6, name: '24cm' },
   { id: 7, name: '24.5cm' },
   { id: 8, name: '25cm' },
   { id: 9, name: '25.5cm' },
   { id: 10, name: '26cm' },
   { id: 11, name: '26.5cm' },
   { id: 12, name: '27cm' },
   { id: 13, name: '27.5cm' },
   { id: 14, name: '28cm' },
   { id: 15, name: '28.5cm' },
   { id: 16, name: '29cm' },
   { id: 17, name: '29.5cm' },
   { id: 18, name: '30cm' }
 ]
  
 include ActiveHash::Associations
 has_many :users
 has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :size

  with_options presence: true do  
    validates :nickname
    validates :birth_day
    validates :profile
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/, message: '全角文字を使用してください' } do
    validates :first_name, presence: true
    validates :last_name,  presence: true
  end

  with_options presence: true, format: { with: /\A[ァ-ヶ]+\z/, message: '全角(カタカナ)を使用してください'} do
    validates :first_name_kana,  presence: true
    validates :last_name_kana,   presence: true
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には半角の英字数字の両方を含めて設定してください'

  validates :size_id, 
  numericality: { other_than: 1, message: 'Select'}

  has_many :items
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth_day, :size_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index   
  end
  
  def new
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with local: true do |f|%>
  <div class="field">
    <%= f.label :hoge, "プロトタイプの名称" %><br />
    <%= f.text_field :hoge %>
  </div>

  <div class="field">
    <%= f.label :hoge, "キャッチコピー" %><br />
    <%= f.text_area :hoge, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :hoge, "コンセプト" %><br />
    <%= f.text_area :hoge, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :hoge, "プロトタイプの画像" %><br />
    <%= f.file_field :hoge %>
  </div>

  <div class="actions">
    <%= f.submit "出品する", class: :form__btn  %>
  </div>
<% end %>

app/views/items/_prototype.html.erb
<div class="card">
  <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to "プロトタイプのタイトル", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "プロトタイプのキャッチコピー" %>
    </p>
    <%= link_to "by プロトタイプの投稿者名", root_path, class: :card__user %>
  </div>
</div>

app/views/items/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
      <%# <div class="greeting"> %>
        <%# こんにちは、 %>
        <%# <%= link_to "ユーザー名さん", root_path, class: :greeting__link%>
      <%# </div> %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
    </div>
  </div>
</main>

app/views/items/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">My Sneakerを出品する</h2>
        <%# 部分テンプレートでフォームを表示する %>

        <%= form_with local: true do |f|%>
        <div class="field">
          <%= f.label :hoge, "商品の画像" %><br />
          <%= f.file_field :hoge %>
        </div>
        
        <div class="field">
          <%= f.label :hoge, "商品のブランド" %><br />
          <%= f.text_field :hoge %>
        </div>

        <div class="field">
          <%= f.label :hoge, "商品説明" %><br />
          <%= f.text_area :hoge, class: :form__text %>
        </div>

        <div class="field">
          Size 
          <%= f.collection_select(:size_id, Size.all, :id, :name, {}, {class:"select-box"}) %>
          </div>

         <div class="field">
          商品の状態 
          <%= f.collection_select(:item_state_id, ItemState.all, :id, :name, {}, {class:"select-box_2"}) %>
          </div>

          <div class="field">
          発送元 
          <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box"}) %>
          </div>
        

      <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div class="box">
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
            <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
          </div>
          </span>
        </div>
       </div>
      </div>

         <div class="actions">
           <%= f.submit "出品する", class: :form__btn  %>
         </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SneakerLovers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
               <%= link_to "出品する", new_item_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">SNAKER LOVERS EST 2021</p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>